[29 김혜린] : 이메일로 이메일유효성, 회원여부 검사
wecode-bootcamp-korea/29-1st-Wesop-backend pull request #4
Opened 2022-01-27 09:26 UTC by OolongTea620

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 1. 클라이언트에서 요청하는 email 파라미터 값이 이메일 형식인지 유효성을 검사한다
- 2. 유효한 이메일인 경우, 이미 웹사이트에 가입된 회원인지 아닌지 검사를 한다
- 3.  만약 유효한 새 이메일인 경우 회원 가입가능하다는 응답을 준다
- 4.  회원 가입시 이메일과 패스워드(영어 대소문자, 숫자  8자이상인 경우에만)  유효성 검사 
- 5. 회원 가입 유효한 경우 회원가입 진행

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 이메일 입력 데이터 유효성 처리 (조건문과 정규식을 이용)
-  email이 형식에 맞는지 확인을 한다
- email이 유효한 형식인 경우 회원 유무를 확인한다
- 클라이언트 측에서 보낼만한 파라미터 예외처리(키 값 없음, body없음,  ' ' 보냄 등)추가
- 만약 유효성을 충족하지 못한 경우 에러 메시지 반환
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 클라이언트가 보낼 수 있는 다양한 오류 경우에 대해 생각하게 되었습니다
- body없는 POST요청을 한번 대처해 보는 기회가 되었습니다
- 에러메시지와 공식문서로 왜 에러가 났는지 추적해볼 수 있었습니다
<br />

## :: 기타 질문 및 특이 사항
- 문자열 맨 끝 공백 외에도 좀 더 기상천외한? 생각해 볼 수 있는 잘못된 데이터의 예시가 있을까요?

2022-01-27 11:04 UTC, lordmyshepherd requested changes

2022-01-27 11:04 UTC, lordmyshepherd commented on users/views.py
> +    """
이제 주석은 지워주세요-!
개발용으로 주석을 다는 것은 좋지만, 실제 코드를 main branch에 머지할때에는 주석없이 코드만 깔끔하게 올라갈 수 있도록 수정해주세요~

2022-01-27 11:04 UTC, lordmyshepherd commented on users/views.py
> +
빈 줄 지워주세요~
```suggestion
```

2022-01-27 11:04 UTC, lordmyshepherd commented on users/views.py
> +
마찬가지로 빈 줄은 지워주세요

2022-01-27 11:04 UTC, lordmyshepherd commented on users/views.py
> +            REG_EMAIL = r'^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$'
변수명을 조금 더 가독성 좋게 수정해주세요~
```suggestion
            data  = json.loads(request.body)
            email = data['email']
            REGEX_EMAIL_RULE = r'^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$'
```

2022-02-05 14:19 UTC, OolongTea620 commented on users/views.py
> +
수정했습니다

2022-02-05 14:19 UTC, OolongTea620 commented on users/views.py
> +            REG_EMAIL = r'^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$'
1. 변수명 다시 이름짓기 완료했습니다

2022-02-05 14:19 UTC, OolongTea620 commented on users/views.py
> +    """
main 브랜치 머지 직전이라 주석삭제 했습니다!

2022-02-07 05:49 UTC, OolongTea620 commented
conflict  해결 완료

2022-02-07 09:38 UTC, lordmyshepherd requested changes

2022-02-07 09:38 UTC, lordmyshepherd commented on users/views.py
> +class CheckEmailView(View) :
code review
```python
import json
import re
import bcrypt
import jwt

from django.views import View
from users.models import User

from django.http import JsonResponse
from django.conf import settings

def validate_email(user):
    REGEX_EMAIL = r'^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$'

    if not re.fullmatch(REG_EMAIL, data["email"]) : 
        raise Validator(error)

REG_PASS  = r'^(?=.*[A-Za-z])(?=.*\d)(?=.*[$@$!%*#?&])[A-Za-z\d$@$!%*#?&]{8,}$'

def check_email(request):
    try :
        data = json.loads(request.body)
        
        if not re.fullmatch(REG_EMAIL, data["email"]) : 
            return JsonResponse({"message" : "잘못된 형식의 이메일 입니다"}, status = 401)

        if User.objects.filter(email = data["email"]).exists() : 
            return JsonResponse({"message" : "이미 존재하는 회원", "sign-in" : 1}, status = 404)

        return JsonResponse({"message" : "유효한 이메일, 가입가능 ", "sign-in" : 0}, status  = 200)
    
    except KeyError :
        return JsonResponse({"message" : "email 키 없음"}, status = 400)

    except json.JSONDecodeError :
        return JsonResponse({"message" : "잘못된형식의 이메일(email파라미터 조차도 없음))"}, status = 401)


class SignUpView (View) :
    @input_validator
    def post(self, request) :
        try :
            data       = json.loads(request.body)
            email      = data['email']
            password   = data['password']
            last_name  = data['last-name']
            first_name = data['first-name']
            name       = last_name + '^' + first_name
            
            if not re.fullmatch(REG_EMAIL, email) :
                return JsonResponse({'message' : 'INVALID_EMIAL'}) 

            if not re.fullmatch(REG_PASS,password) :
                return JsonResponse({'message' : '유효하지 않은 패스워드'},status = 401)

            if User.objects.filter(email__exact = email).exists() :
                return JsonResponse({"message" : "이미 가입된 이메일"}, status = 400)

            User.objects.create(
                email = email,
                password = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8'),
                name = name
            )

            return JsonResponse({"message" : "SUCCESS"}, status = 201)
        
        except KeyError :
            return JsonResponse({"message" : "KEY_ERROR"}, status = 400)

        except json.JSONDecodeError :
            return JsonResponse({"message" : "INVALID_REQUEST_BODY"}, status = 400)

class LoginView (View) :
    @input_validator
    def post (self , request) : 
        try :
            data = json.loads(request.body)
            user = User.objects.get(email__exact = data['email'])
            
            if bcrypt.checkpw(data['password'].encode('utf-8'), user.password.encode('utf-8')):
                access_token = jwt.encode({'id': user.id}, settings.SECRET_KEY, settings.algorithm = ALGORITHM)
                return JsonResponse({ 'message': 'SUCCESS','ACCESS_TOKEN' : access_token}, status = 200)

            return JsonResponse({"message": "로그인 실패"}, status = 401)

        except KeyError :
            return JsonResponse({"message": "KEY_ERROR"}, status = 400)

        except User.DoesNotExist :
            return JsonResponse({"message ": "가입되지 않은 이메일"}, status = 400)

        except json.JSONDecodeError:
            return JsonResponse({"message" : "no-body"}, status = 400)
```

2022-02-08 01:25 UTC, closed without merging