[혜린] C
wecode-bootcamp-korea/29-1st-Wesop-backend pull request #9
Opened 2022-02-09 07:35 UTC by OolongTea620

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로그인 입력 데이터 유효성 검사 (예시 - 프론트)
- 입력창에 변화가 일어날 때 마다 유효성 검사 함수가 실행된다.
- 유효성 검사 함수의 반환값(boolean)에 따라 버튼의 배경색과 disabled 속성이 변화한다.
- 테스트 방법 : `/login` 페이지 이동 >>> 로그인 input 데이터 입력

2. 로그인 데이터 처리 (예시 - 백엔드)
- 조건문과 정규식을 이용한 email과 password 유효성 검사를 진행
- 유효섬 검사를 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-02-09 08:03 UTC, lordmyshepherd requested changes

2022-02-09 08:03 UTC, lordmyshepherd commented on carts/views.py
> +class GetCartListView(View) :
**피드백 1.**
`GetCartListView`, `AddCartView`, `UpdateCartView`,  `DeleteCartView`가 전부 각각의 class로 구현이 되어 있습니다.
이렇게 구현할거면 함수로 구현하는게 효율적이겠죠. class를 사용하는 이유가 무엇인가요? 같은 Entity 까리 묶기 위함이죠?

`CartView` class 안에 전부 합쳐주세요.
```python
class CartView:
    def get ..
    def post ..
    def patch ..
    def delete
```

2022-02-09 08:03 UTC, lordmyshepherd commented on carts/views.py
> +    def get(self, request, user_id) :
**피드백 2.**
유저 id를 URI를 통해서 직접 받으면 안됩니다. client에서 cart 정보를 조회할 때 보내준 acess_token에서 사용자 정보를 꺼내와서 사용하도록 수정해주세요.

`@login_required` 데코레이터를 붙여야 겠죠?
cart 관련된 get, post, update, delete 모두 login_reqired 데코레이터가 붙여 있어야 합니다.
없다면, 로그인 하지 않은 사람들도 마음대로 카트에 추가하고 다른 사람의 카트 정보까지 볼 수 있겠죠?

인증/인가 개념을 다시한번 확인해부시면 좋을 것 같아요~

2022-02-09 08:03 UTC, lordmyshepherd commented on carts/views.py
> +        items   = Cart.objects.filter(user_id = user).all().select_related('product').all().select_related('product').all()
select_related 함수를 왜 두번 사용한건가요?
```suggestion
        items   = Cart.objects.filter(user_id = user).all().select_related('product').all().select_related('product').all()
```

2022-02-09 08:03 UTC, lordmyshepherd commented on carts/views.py
> +        result['message'] = "SUCCESS"
**피드백 3.**
- 불필요한 코드들이 읽어야될 코드 수를 늘리고 있습니다.
- 명확한 변수명을 사용해주세요.
- 변수명을 정할때, 변수에 담기는 값이 하나인지 복수인지 고려하시고 단수/복수를 명확하게 지켜주세요. 

```suggestion

        results = [
            {
            "cart_id" : cart.id
            "product_options_id" : cart.product.id,
            ...
            } for cart in carts
        ]
```

2022-02-09 08:03 UTC, lordmyshepherd commented on carts/views.py
> +        product = [
**피드백 4.**
카트 정보를 요청했으면 카트 테이블에 있는 정보도 같이 반환해주도록 합니다.

2022-02-09 08:03 UTC, lordmyshepherd commented on carts/views.py
> +            return JsonResponse({"message" : "KEY_ERROR"}, status= 400)
RESTful하게 API를 만들기 위해서는 자원을 지울때, delete할 때, path parameter로 cart_id를 받아서 지우도록 만들어주세요.
다음과 같이 URI만 보고도 해당 자원에 어떤 작업을 수행하는지 알 수 있어야 합니다.~ `DELETE :8000/carts/1`

```suggestion
class DeleteCartView (View) :
    
    @validate_cartdata
    def post(self, request) :
        try :
            data = json.loads(request.body)['message']
            success  = Cart.objects.filter(
                user_id=data['user_id'],
                product_id=data['product_options_id']
            ).delete()
            if success == 0 :
                return JsonResponse({"message" : "DELETE_FAIL"}, status= 400)
            return JsonResponse({"message" : "DELETE_SUCCESS"}, status= 400)
        except KeyError :
            return JsonResponse({"message" : "KEY_ERROR"}, status= 400)
```

2022-02-09 08:26 UTC, OolongTea620 commented on carts/views.py
> +        items   = Cart.objects.filter(user_id = user).all().select_related('product').all().select_related('product').all()
1. Carts(장바구니)모델에 있는 product 어트리뷰트는 정확하게 product_option 테이블의 id를 외래키로 참조합니다.
2. product_Option 모델 product 어트리뷰트는 Product 모델 id에 접근하는 외래키 어트리뷰트 입니다
3. 결론적으로 Product모델 안에 있는 name(제품이름을 저장하는 어트리뷰트)을 가져와야 해서
4. 2번 정참조를 위해서  (Cart --['product']--> Product_Option--['product']'--> Product) 사용했습니다

2022-02-10 07:21 UTC, walkersmind commented on carts/views.py
> +            product_option  = ProductOption.objects.get(id = product_option_id)
컨벤션 확인하셔서 띄어쓰기 맞춰주시면 좋을 거 같습니다!

2022-02-10 08:52 UTC, closed without merging